import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/layout/Navbar";
import { ThemeProvider } from "./providers/themeProvider";
import { Toaster } from "sonner";
import flower from   "../../public/flower.jpg"
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en " suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            
            {children}
          <Toaster richColors/>
           
          </ThemeProvider>
          {/* {children} */}
        <h1>This is root text </h1>
        {/* <img src="https://images.pexels.com/photos/10047055/pexels-photo-10047055.jpeg" alt="" /> */}
        <div className="relative w-full  h-[200px] md:h-[400px] lg:h-[500px]">
          {/* <Image   src={flower} fill alt="Hero" className="object-cover rounded-md" /> */}
          <Image src="https://images.pexels.com/photos/10047055/pexels-photo-10047055.jpeg" fill alt="Hero"  className=" rounded-md "/>
        </div>
        
          
        
        
      </body>
    </html>
  );
}
